#run command -> docker compose -f elasticsearch.yml up

#version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    volumes:
      - /home/ameya/Apps/elastic/docker/data:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch