version: "3"
services:
   kafka-1:
     image: 'bitnami/kafka:latest'
     ports:
       - '9092:9092'
       - '19092:19092'
     volumes:
       - /home/ameya/Apps/kafka/data/server-1:/bitnami/kafka
     environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19092
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.29.206:9092
       - KAFKA_CFG_NODE_ID=1
       - KAFKA_CFG_BROKER_ID=1
       - ALLOW_PLAINTEXT_LISTENER=yes
       - BITNAMI_DEBUG=true
       - KAFKA_KRAFT_CLUSTER_ID=b8tRS7h4TJ2Vt43Dp85v2A
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094

   kafka-2:
     image: 'bitnami/kafka:latest'
     ports:
       - '9093:9093'
       - '19093:19093'
     volumes:
       - /home/ameya/Apps/kafka/data/server-2:/bitnami/kafka
     environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,CONTROLLER://:19093
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.29.206:9093
       - KAFKA_CFG_NODE_ID=2
       - KAFKA_CFG_BROKER_ID=2
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094
       - ALLOW_PLAINTEXT_LISTENER=yes
       - BITNAMI_DEBUG=true
       - KAFKA_KRAFT_CLUSTER_ID=b8tRS7h4TJ2Vt43Dp85v2A

   kafka-3:
     image: 'bitnami/kafka:latest'
     ports:
       - '9094:9094'
       - '19094:19094'
     volumes:
       - /home/ameya/Apps/kafka/data/server-3:/bitnami/kafka
     environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:19094
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.29.206:9094
       - KAFKA_CFG_NODE_ID=3
       - KAFKA_CFG_BROKER_ID=3
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094
       - ALLOW_PLAINTEXT_LISTENER=yes
       - BITNAMI_DEBUG=true
       - KAFKA_KRAFT_CLUSTER_ID=b8tRS7h4TJ2Vt43Dp85v2A
